### ISSUE TITLE
Unable to run any other script than start

### ISSUE THREAD

**Issue by sambhav-gore** [kitze/JSUI#103]
I am liking this tool and it will really help me as I have to concurrently run multiple apps from different repositories.

I imported projects and I am able to start them both individually and all at once (they all have script `yarn start`).
I am however unable to run any other scripts for the projects. I really need to be able to run `yarn start:dev` for each of the project when I am working on those.

Am I doing something wrong ? 
I see all the scripts in the UI but nothing happens when I click on those.

**Comment by dkrvl** [comment]
@kitze  Giving me error when running NPM Start or YARN start

**Comment by sambhav-gore** [comment]
I pulled master again and now I am able to run specific scripts.
