### ISSUE TITLE
Use github icon for links to github repos (the same for bitbucket, gitlab...)

### ISSUE THREAD

**Issue by juanmaguitar** [kitze/JSUI#104]
I think it would be more intuitive to use the correspondent brand logo for links pointing to repos.

- Github icon for links pointing to github repos.
- Bitbucket icon for links pointing to bitbucket repos.
- Gitlab icon for links pointing to gitlab repos.

They're all available at https://fontawesome.com/icons?d=gallery&s=brands that i think is already a dependency of the project

Other ones (that can't be easily categorized) can maintain a generic logo like the one being used already.

**Comment by kitze** [comment]
Good suggestion, done.
