### ISSUE TITLE
When start app: Error: Could not get code signature for running application

### ISSUE THREAD

**Issue by tieorange** [kitze/JSUI#112]
Unhandled Error
Error: Could not get code signature for running application
    at initUpdater (/Applications/JSUI.app/Contents/Resources/app.asar/node_modules/update-electron-app/index.js:47:15)
    at App.opts.electron.app.isReady.opts.electron.app.on (/Applications/JSUI.app/Contents/Resources/app.asar/node_modules/update-electron-app/index.js:32:43)

**Comment by shockw4ver** [comment]
There's a way to resolve this by building it from source code.

I resolve this by delete some code about ``autoUpdate``, for an app must be signed to enable this service.

I found the those code in **electron/electron.js**:
```javascript
//...
const initAutoUpdate = require('update-electron-app');
//...
initAutoUpdate({
  repo: 'kitze/jsui'
})
```

Remove them and build, it works.

However it must to sign by anyway to enjoy the autoUpdate service.

**Comment by kitze** [comment]
This release should be fine:

https://github.com/kitze/JSUI/releases/tag/v0.0.18
