### ISSUE TITLE
Startup error after installation (on macos high sierra)

### ISSUE THREAD

**Issue by dpkshrma** [kitze/JSUI#115]
I downloaded latest version ([JSUI-0.0.18.dmg](https://github.com/kitze/JSUI/releases/download/untagged-99de79086473c0c15e56/JSUI-0.0.18.dmg)) but after installation, when I tried to open it, I got the below error:

```
Unhandled Error
Error: Could not get code signature for running application
    at initUpdater (/Applications/JSUI.app/Contents/Resources/app.asar/node_modules/update-electron-app/index.js:47:15)
    at App.opts.electron.app.isReady.opts.electron.app.on (/Applications/JSUI.app/Contents/Resources/app.asar/node_modules/update-electron-app/index.js:32:43)
```
Do I need to install electron first for it to work?
AFAIK electron apps get bundled with it as a dependency be default (i might be wrong)

**Comment by kitze** [comment]
Please try this release:
https://github.com/kitze/JSUI/releases/tag/v0.0.18

**Comment by dpkshrma** [comment]
Sorry about the dead link. But, that is exactly what I was using.

Although, I got it working after installing 0.0.17 which auto upgraded to latest.

**Comment by kitze** [comment]
Awesome!
