### ISSUE TITLE
App title incorrect word wrap

### ISSUE THREAD

**Issue by shanepadgett00** [kitze/JSUI#116]
I'm getting a word wrap bug causing overflow outside of the projects container.

![image](https://user-images.githubusercontent.com/29068876/41866392-99cf2f30-7875-11e8-9633-5779cca2b890.png)

**Comment by kitze** [comment]
Just rename the project. This is a Windows bug and I won't tackle other platforms until the project is [properly funded](https://opencollective.com/jsui)
