### ISSUE TITLE
yarn build failing

### ISSUE THREAD

**Issue by greg-benner-klick-sensei** [kitze/JSUI#119]
Environment Windows 10, and Node 10.x
---
First installed https://github.com/facebook/create-react-app/issues/4356 to fix "Chunk.entrypoints: Use Chunks.addGroup instead"
---
```
Failed to minify the code from this file:

        ./node_modules/transform-css-to-js/dist/index.js:33

Read more here: http://bit.ly/2tRViJ9
```

**Comment by Imfdj** [comment]
me too
