### ISSUE TITLE
Can't generate project 

### ISSUE THREAD

**Issue by kitze** [kitze/JSUI#122]

**Comment by elijahmanor** [comment]
![jsui-create-fail](https://user-images.githubusercontent.com/86454/44408816-c2c79480-a526-11e8-876d-142659c930e5.gif)

I'm unable to generate a project using v0.0.18 on macOS. I tried several templates (create-react-app, preact, vue), but none of them would generate for me.

Initially I didn't have yarn installed, so I went ahead and installed yarn thinking that might be the cause, but that did not fix the issue either.

From what I can tell, a embedded terminal is supposed to come up after the create button is clicked, but it doesn't come up on my machine.

NOTE: I tried the following 2 configurations of node and npm

* ⬢ v8.9.4 	📦 5.6.0
* ⬢ v8.11.3	📦 6.4.0

**Comment by kitze** [comment]
Resolved this over Twitter DMs, the problem was create-react-app must be installed globally on the machine. Will use npx soon.
