### ISSUE TITLE
Kitze.io link to the JSUI

### ISSUE THREAD

**Issue by Eghizio** [kitze/JSUI#134]
The link to the JSUI on [Your page](https://kitze.io/) points to [jsui user profile](https://github.com/jsui) not the [JSUI project repository](https://github.com/kitze/JSUI).
 
Didn't know where to send it as I don't have Twitter :D

tl;dr change https://github.com/jsui to https://github.com/kitze/JSUI on ur https://kitze.io/ page on the left navigation.

**Comment by kitze** [comment]
Thank you @Eghizio!
