### ISSUE TITLE
Allow user to choose between yarn and npm

### ISSUE THREAD

**Issue by kitze** [kitze/JSUI#14]

**Comment by mindmergedesign** [comment]
ditto

**Comment by jakedohm** [comment]
I could take a swing at implementing this, as it should be fairly easy!

@kitze do you think this should be implemented on a user setting level, or on each project?

Maybe the user should set their default, and then there could be an option on each project so they could use NPM on one and Yarn on another. What do you think?

**Comment by jakedohm** [comment]
@KSXGitHub right, good thoughts!

So, the best way to implement is probably:

- When importing an existing project, use whatever the project is currently using. If there's no lock file, then use the default package manager (from user settings).
- When starting a new project, ask which package manager to use (this is already implemented), and then use that going forward for dep. management and running scripts (this **doesn't** work, it uses `yarn` for scripts, even if `npm` was selected when the project was created).

Should there also be an option to _switch_ dependency managers, that will clear out node_modules, and then install them with the newly selected package manager.

If this sounds fine to @kitze and/or @rakannimer, I'd love to move forward with implementing. What do y'all think?

**Comment by kitze** [comment]
ffs I'm typing a new reply for the 20th time and I just can't settle on which solution we should go with. I'll think about this tomorrow, so don't proceed with any work yet

**Comment by KSXGitHub** [comment]
@kitze How about this:

1. If the project uses 1 lock file, JSUI automatically determines package manager. If the project uses 0 or 2+ lock files, proceed step 2.

2. Show user a dialog box that asks for package manager. The dialog box has a "Don't ask me again" checkbox.

**Comment by ghengeveld** [comment]
Maybe also consider the `engines.npm` value in `package.json`:

```json
"engines": {
  "node": "9.x",
  "npm": "5.x"
}
```

**Comment by kitze** [comment]
Good suggestion @ghengeveld. But this assumes npm and has no option to use yarn?

**Comment by ghengeveld** [comment]
You can do:

```json
"engines": {
  "yarn": "1.x"
}
```

**Comment by jakedohm** [comment]
@ghengeveld unless I'm misunderstanding something, the Google App Engine actually _doesn't_ look at the `engines` property to decide which package manager to use. It only looks at that to decide what _version_ of the package manager to use.

See [this section](https://cloud.google.com/appengine/docs/flexible/nodejs/runtime#package_manager) to see how they decide which package manager to use.

Based on my earlier suggestion, and that section from the Google App Engine, I think the best way to implement this is:
- When importing an existing project, use whatever the project is currently using (based on lock files). If there's no lock file, or multiple lock files, then use the user default package manager (or just ask which to use).
- When starting a new project, ask which package manager to use, and then use that going forward for dependency management and running scripts

I think this solution works best as it is simple, requires as little interaction from the user as possible.
