### ISSUE TITLE
Mark projects as favorites and put favorites on top (configurable in settings)

### ISSUE THREAD

**Issue by kitze** [kitze/JSUI#20]

**Comment by sallespro** [comment]
Besides favoriting projects, i often need to group projects in stacks, so your `groups` may offer some structure to support that. i.e. front/back end, API, docs... hopefully in such a way it can offer some visibility of its components, like a `docker-compose.yml` file structure does.

Another thing is being able to visualize some sort of timeline, that helps you identify what the hell one has been spending time with, not to look for efficiency but to recognize one's own interests.

**Comment by kitze** [comment]
@sallespro I was thinking about this too. Will add it soon.

**Comment by sallespro** [comment]
i regret mixing too many concepts. do you mean stacks/docker_compose OR the timeline ?
