### ISSUE TITLE
Add "install dependencies" button

### ISSUE THREAD

**Issue by jakedohm** [kitze/JSUI#46]
I was just trying to run `yarn run dev` on a project that I had just cloned down, and hadn't run `yarn` or `npm install` so it wouldn't work. All that to say, I think a "install dependencies" button is needed.

I saw issue #8 also, so there may be a good way to group these together.

Probably worth noting also that the install/reinstall buttons should honor the assigned dependency manager (#14)

I'd be glad to help implement this if you're interested.

**Comment by jakedohm** [comment]
@kitze love the way you implemented this! Feel free to close this whenever 😄

**Comment by kitze** [comment]
Oh, forgot to close it. Tnx!
