### ISSUE TITLE
Child process stays open on exit

### ISSUE THREAD

**Issue by just-boris** [kitze/JSUI#54]
I am using the latest  version "0.0.13 (0.0.13)" on Mac OS.

Steps to reproduce:

1. Open a project, run `start` command.
2. Close JSUI

Expected result: all child processes are getting closed too

Actual result: there is a hanging `yarn start` process that has to be killed manually

**Comment by kitze** [comment]
Thanks @just-boris. It will land in the new release today along with many other process improvements.
