### ISSUE TITLE
Determine if the project is open source or not

### ISSUE THREAD

**Issue by kitze** [kitze/JSUI#58]
Is this possible to determine from the `.git` config?

**Comment by rakannimer** [comment]
I don't think it is. 

What do you think about sending a network request to the repo url and check if it returns a 403 ?

**Comment by Manavjs** [comment]
@rakannimer As far as I know, a request returning 200 only means that the repository is public. And GitHub defaults the licenses of a public repository to "all rights reserved" and thus, not open source...so this method will not work on its lonesome.

A way to check for open source licensing would be to look for LICENSE.md in the project and look for certain keystrings, like "without limitation", which is found in both the [MIT license](https://en.wikipedia.org/wiki/MIT_License) and the [BSD license](https://en.wikipedia.org/wiki/BSD_licenses) standards.
