### ISSUE TITLE
Start all projects in a group

### ISSUE THREAD

**Issue by GabeAtWork** [kitze/JSUI#59]
Hey guys, JSUI is a very neat tool!

One feature which would be very useful for my company's use case would be a "start group" button that executes `start` on each project of the group.

I'd be interested in helping in making this feature happen!

**Comment by kitze** [comment]
Hey Gabe. Thanks for the suggestion. This is planned for tomorrow but I have a different idea for executing it.

**Comment by kitze** [comment]
Released in 0.0.15
