### ISSUE TITLE
Add app to homebrew cask

### ISSUE THREAD

**Issue by xeoneux** [kitze/JSUI#66]
This would make it really easy for installation and removal

**Comment by kitze** [comment]
how

**Comment by glennreyes** [comment]
https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md

Can be installed to your machine then with eg. `brew cask install jsui`

**Comment by yannbertrand** [comment]
[Done](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/jsui.rb)!

**Comment by kitze** [comment]
Nice, good stuff @yannbertrand !
