### ISSUE TITLE
Allow user to add descriptions for npm scripts in package.json

### ISSUE THREAD

**Issue by kitze** [kitze/JSUI#81]

**Comment by siddharthkp** [comment]
Probably piggyback on https://github.com/kentcdodds/nps ?

**Comment by kitze** [comment]
nps makes so much sense compared to writing scripts in package.json...

But I still want to support plain old package.json files. Currently trying to parse all possible variations of nps-run-all with regex and it's a nightmare.

**Comment by kitze** [comment]
Also, a lot of people already use [npm-scripts-info](https://www.npmjs.com/package/npm-scripts-info) to provide a description for the scripts:

So I decided to also read the descriptions from the `scripts-info` property.
