### ISSUE TITLE
Add some hotkeys for quick navigation

### ISSUE THREAD

**Issue by Rubyroidas** [kitze/JSUI#93]
For example:
- ⌘+F: search by name
- arrows: navigate through search results
- Enter: edit code for selected project
- Esc: quit search by name field; also return to home screen from project view

**Comment by kitze** [comment]
You can already do this:

Cmd + Shift + P is navigating by project
When you're in a project you can press Cmd + Shift + A and execute quick actions like "run script" or "edit code" or "open in finder"
Cmd + Shift + H is return to home screen
Cmd + SHift + N is for searching project files

I should document the shortcuts somewhere..

**Comment by Rubyroidas** [comment]
can you make keys less complicated please? :) I mean 2 key, not 3 key combos

**Comment by Rubyroidas** [comment]
Also, `Cmd + Shift + N` is not trivial as for search hotkey, it looks like a `new file` command rather than a search o_O

**Comment by kitze** [comment]
https://github.com/kitze/JSUI/issues/7

Soon.
